name: publish
on:
  push:
    tags:
      - v*
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        rust: [nightly, beta, stable]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{matrix.rust}}
          profile: minimal
      - name: Run Tests
        run: cargo test
  publish:
    runs-on: ubuntu-20.04
    needs: [test]
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - uses: olegtarasov/get-tag@v2.1
        id: tagName
        name: Get Tag Name
        with:
          tagRegex: "v(?<version>.*)"
      - name: Set Package Version
        env:
          GIT_TAG_NAME: ${{ steps.tagName.outputs.version }}
        run: sed -i "s/version = \"0.1.0\"/version = \"${GIT_TAG_NAME}\"/" Cargo.toml
      - name: Cargo Login
        env:
          CARGO_TOKEN: ${{ secrets.CARGO_TOKEN }}
        run: cargo login $CARGO_TOKEN
      - name: Cargo Publish Dry Run
        run: cargo publish --dry-run
      - name: Cargo Publish
        run: cargo publish
